### ISSUE TITLE
No output in qemu

### ISSUE THREAD

**Issue by copy** [xorvoid/sectorc#14]
None of the following produce any output (neither on the serial console, nor vga console, nor audio):

```
./run_raw.sh examples/hello.c
./run_raw.sh examples/sinwave.c
./run_raw.sh examples/twinkle.c
```

I only changed `coreaudio` to `pa` in run_raw.sh. This is on qemu 8.0.4 on Linux. The `build/sectorc.bin` file matches the base64 in the readme. Is there any sort of debug mode?

**Comment by xorvoid** [comment]
I'm not sure how to reproduce this as I don't have a Linux machine currently. Hanging would be due to it not reading anything from serial. I would suggest writing a small serial program in asm and debugging there.

The serial code in question is this:
```
getch_tryagain:
  mov ax,0x0200
  xor dx,dx
  int 0x14                      ; get a char from serial (bios function)

  and ah,0x80                   ; check for failure and clear ah as a side-effect
  jne getch_tryagain            ; failed, try again later

  cmp al,59                     ; check for ';'
  jne getch_done                ; if not ';' return it
  mov [si],ax                   ; save the ';'
  xor ax,ax                     ; return 0 instead, treated as whitespcae

getch_done:
  pop dx
  ret
```

This function can be simplified a tad (it does some tricks to inject spaces in front of ';' chars)

**Comment by copy** [comment]
My bad. I was using run_raw.sh rather than run.sh (the former doesn't include lib.c).
